all: 
	D:\Git\GitHub\Cpp\Kompilator_skrosny\main.exe -i main.mpc -o main_mpc.c -v -t -1 -l ../../Libs/MATLAB/ -L ../../Libs/C/
	#/d/Git/GitHub/Cpp/Kompilator_skrosny/main.exe

run:
	gcc ./*.c ../../Libs/C/*.c -I ../../Libs/C/ -g -o ./a.out
	./a.out
